version: '3.8'
services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
  frontend:
    build:
      context: ./frontend
      args:
        - API_BASE_URL=http://127.0.0.1:8000
    ports:
      - "80:80"